#!/usr/bin/env python3
# use configuration files for projects
import os
import logging

from openppl_creator_lib import get_oppl_files

logging.root.setLevel(logging.INFO)

import argparse

DESCRIPTION = "OpenPPL creator is a program to create a .oppl script from different files."

output_file_name = '{0}.oppl'.format(os.path.split(os.getcwd())[1])
input_path = 'src'
output_path = 'out'


parser = argparse.ArgumentParser(description=DESCRIPTION)

for debug_arg in ['-d', '--debug']:
    parser.add_argument(debug_arg, dest='debug', action='store_true', help='Set logging level to DEBUG.')


if __name__ == '__main__':
    args = parser.parse_args()
    if args.debug:
        logging.root.setLevel(logging.DEBUG)

    current_path = os.getcwd()

    abs_input_path = os.path.join(current_path, input_path)

    oppl_files = get_oppl_files(abs_input_path)

    abs_output_path = os.path.join(current_path, output_path)

    if not os.path.exists(abs_output_path):
        os.makedirs(abs_output_path)

    scripts = [script for function, script in oppl_files.items()]
    separator = "\n"
    final_script = separator.join( scripts)

    logging.info("Creating final file: %s", output_file_name)
    with open(os.path.join(abs_output_path, output_file_name), 'w') as output_file:
        output_file.write(final_script)

    logging.info("Completed!")
